name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch WakaTime Stats
        run: |
          # Fetch JSON data from WakaTime API
          curl -s "https://wakatime.com/api/v1/users/current/stats/all_time?api_key=${{ secrets.WAKATIME_API_KEY }}" | jq '.' > wakatime.json
          
          # Extract total time (directly use the human-readable format)
          TOTAL_TIME=$(jq -r '.data.human_readable_total // "0 hrs 0 mins"' wakatime.json)
          
          # Extract language statistics
          LANGUAGES=$(jq -r '.data.languages[] | "\(.name): \(.percent)%"' wakatime.json | sort -k2 -nr)

          # Debugging output
          echo "Total Coding Time: $TOTAL_TIME"
          echo "Languages Used: $LANGUAGES"

          # Save output to file
          echo -e "Total Coding Time : $TOTAL_TIME\n\nLanguages Used:\n$LANGUAGES" > waka-stats.txt

      - name: Update README
        run: |
          TOTAL_OUTPUT=$(cat waka-stats.txt)
          echo "Updating README with: $TOTAL_OUTPUT"
          
          # Update README.md between markers
          sed -i "/<!--START_WAKATIME-->/, /<!--END_WAKATIME-->/c\<!--START_WAKATIME-->\n$(cat waka-stats.txt)\n<!--END_WAKATIME-->" README.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "itsnotTalha"
          git config --global user.email "talhajubayer737@gmail.com"
          git add README.md
          git status  # Debugging
          git commit -m "Updated WakaTime stats" || echo "No changes to commit"
          git push origin main
