name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug WakaTime API Response
        run: |
          curl -s "https://wakatime.com/api/v1/users/current/stats/all_time?api_key=${{ secrets.WAKATIME_API_KEY }}" | jq '.' > wakatime.json
          cat wakatime.json  # Print full response for debugging

      - name: Fetch WakaTime Stats
        run: |
          TOTAL_SECONDS=$(jq -r '.data.total_seconds // 0' wakatime.json)
          TOTAL_HOURS=$((TOTAL_SECONDS / 3600))
          TOTAL_MINUTES=$(( (TOTAL_SECONDS % 3600) / 60 ))
          TOTAL_TIME="Total Coding Time : ${TOTAL_HOURS} hrs ${TOTAL_MINUTES} mins"
          echo "$TOTAL_TIME"
          echo "$TOTAL_TIME" > waka-stats.txt

      - name: Update README
        run: |
          TOTAL_TIME=$(cat waka-stats.txt)
          sed -i "/<!--START_WAKATIME-->/, /<!--END_WAKATIME-->/c\<!--START_WAKATIME-->\n$TOTAL_TIME\n<!--END_WAKATIME-->" README.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "itsnotTalha"
          git config --global user.email "talhajubayer737@gmail.com"
          git add README.md
          git commit -m "Updated WakaTime stats" || echo "No changes to commit"
          git push origin main
