name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch WakaTime Stats
        run: |
          # Fetch JSON data from WakaTime API
          curl -s "https://wakatime.com/api/v1/users/current/stats/all_time?api_key=${{ secrets.WAKATIME_API_KEY }}" | jq '.' > wakatime.json
          
          # Extract total time (in seconds)
          TOTAL_SECONDS=$(jq -r '.data.total_seconds // 0' wakatime.json)

          # Load previous total time if exists, else start from 0
          if [ -f total_time.txt ]; then
            PREVIOUS_TOTAL=$(cat total_time.txt)
          else
            PREVIOUS_TOTAL=0
          fi

          # Add the new total coding time to the previous total
          NEW_TOTAL=$((PREVIOUS_TOTAL + TOTAL_SECONDS))

          # Convert total seconds to human-readable format (H:M:S)
          TOTAL_HOURS=$((NEW_TOTAL / 3600))
          TOTAL_MINUTES=$(((NEW_TOTAL % 3600) / 60))

          # Save the updated time
          echo "$NEW_TOTAL" > total_time.txt
          echo "Total Coding Time : ${TOTAL_HOURS} hrs ${TOTAL_MINUTES} mins" > waka-stats.txt

      - name: Update README
        run: |
          TOTAL_OUTPUT=$(cat waka-stats.txt)
          echo "Updating README with: $TOTAL_OUTPUT"
          
          # Update README.md between markers
          sed -i "/<!--START_WAKATIME-->/, /<!--END_WAKATIME-->/c\<!--START_WAKATIME-->\n$TOTAL_OUTPUT\n<!--END_WAKATIME-->" README.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "itsnotTalha"
          git config --global user.email "talhajubayer737@gmail.com"
          git add README.md total_time.txt
          git commit -m "Updated cumulative WakaTime coding stats" || echo "No changes to commit"
          git push origin main
