name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch WakaTime Stats
        run: |
          curl -s "https://wakatime.com/api/v1/users/current/stats/all_time?api_key=${{ secrets.WAKATIME_API_KEY }}" > wakatime.json
          TOTAL_TIME=$(jq -r '.data.human_readable_total' wakatime.json)
          echo "Total Coding Time : $TOTAL_TIME"
          echo "Total Coding Time : $TOTAL_TIME" > waka-stats.txt


      - name: Update README
        run: |
          sed -i "/<!--START_WAKATIME-->/, /<!--END_WAKATIME-->/c\<!--START_WAKATIME-->\n$(cat waka-stats.txt)\n<!--END_WAKATIME-->" README.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "itsnotTalha"
          git config --global user.email "talhajubayer737@gmail.com"
          git remote set-url origin https://itsnotTalha:${{ secrets.GH_PAT }}@github.com/itsnotTalha/itsnotTalha.git
          git commit -m "Updated WakaTime stats" || echo "No changes to commit"
          git push origin main
